CREATE TABLE employees (
    emp_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR2(50),
    last_name   VARCHAR2(50),
    email       VARCHAR2(100) UNIQUE,
    hire_date   DATE DEFAULT SYSDATE,
    salary      NUMBER(10,2)
);


-- Insert a single record
INSERT INTO employees (first_name, last_name, email, salary)
VALUES ('John', 'Doe', 'john.doe@example.com', 5000);

-- Insert multiple records
INSERT ALL
    INTO employees (first_name, last_name, email, salary) VALUES ('Jane', 'Smith', 'jane.smith@example.com', 6000)
    INTO employees (first_name, last_name, email, salary) VALUES ('Mark', 'Lee', 'mark.lee@example.com', 5500)
SELECT 1 FROM dual;

COMMIT;


-- Select all employees
SELECT * FROM employees;

-- Select specific columns
SELECT emp_id, first_name, salary FROM employees;

-- Filtering
SELECT * FROM employees WHERE salary > 5500;

-- Order results
SELECT * FROM employees ORDER BY hire_date DESC;


-- Update salary of an employee
UPDATE employees
SET salary = 7000
WHERE emp_id = 1;

-- Update multiple fields
UPDATE employees
SET salary = salary + 500, email = 'john.doe@company.com'
WHERE last_name = 'Doe';

COMMIT;


-- Delete a specific employee
DELETE FROM employees WHERE emp_id = 2;

-- Delete by condition
DELETE FROM employees WHERE salary < 5500;

COMMIT;


DROP TABLE employees PURGE;
